-- 자식 노드가 없는 아이템을 출력해야 한다 PARENT_ITEM_ID에 존재하지 않는다면 끝
SELECT I.ITEM_ID, I.ITEM_NAME, I.RARITY FROM ITEM_INFO I JOIN ITEM_TREE T ON I.ITEM_ID = T.ITEM_ID
WHERE NOT EXISTS (
    SELECT T.ITEM_ID FROM ITEM_TREE T
    WHERE T.PARENT_ITEM_ID = I.ITEM_ID
)
ORDER BY I.ITEM_ID DESC
