-- 코드를 입력하세요
SELECT DATE_FORMAT(O.SALES_DATE, "%Y") AS "YEAR", 
MONTH(O.SALES_DATE) AS "MONTH",
COUNT(DISTINCT O.USER_ID) AS "PURCHASED_USERS",
ROUND(COUNT(DISTINCT O.USER_ID) / (SELECT COUNT(*) FROM USER_INFO WHERE JOINED LIKE "2021%"), 1) AS "PUCHASED_RATIO"
FROM ONLINE_SALE O
JOIN USER_INFO U
ON U.USER_ID = O.USER_ID
WHERE U.JOINED LIKE "2021%"
GROUP BY YEAR, MONTH
ORDER BY YEAR ASC, MONTH ASC