SELECT F.FLAVOR FROM (
SELECT FLAVOR, SUM(TOTAL_ORDER) AS FSUM FROM FIRST_HALF GROUP BY FLAVOR) F
LEFT JOIN (
SELECT FLAVOR, SUM(TOTAL_ORDER) AS JSUM FROM JULY GROUP BY FLAVOR) J
ON F.FLAVOR = J.FLAVOR
ORDER BY (FSUM + JSUM) DESC
LIMIT 3